#!/bin/bash

version=`cat dist/version`
bucket="s3://setlister-${SERVER_ENV-dev}-${SERVER_REGION-ue1}-assets"

PARAMS=''
if [ ! -z "$PROFILE" ]; then
  PARAMS="--profile $PROFILE"
fi

# aws s3 cp $PARAMS --recursive --acl public-read "src/assets/font" "$bucket/font" --metadata-directive REPLACE --cache-control max-age=86400
echo "aws s3 cp $PARAMS --recursive --acl public-read --exclude "*.gz.*" "dist/$version" "$bucket/$version" --metadata-directive REPLACE --cache-control max-age=86400"
aws s3 cp $PARAMS --recursive --acl public-read --exclude "*.gz.*" "dist/$version" "$bucket/$version" --metadata-directive REPLACE --cache-control max-age=86400
echo "aws s3 cp $PARAMS --recursive --acl public-read --content-encoding gzip --exclude "*" --include "*.gz.*" "dist/$version" "$bucket/$version" --metadata-directive REPLACE --cache-control max-age=86400"
aws s3 cp $PARAMS --recursive --acl public-read --content-encoding gzip --exclude "*" --include "*.gz.*" "dist/$version" "$bucket/$version" --metadata-directive REPLACE --cache-control max-age=86400
